dist: xenial # required for Python >= 3.7
language: python
python:
  - "3.7"
sudo: false
os:
    - linux
branches:
  only:
    - ui

env:
  global:
    secure: "xkQXZXrchGxi/pUUresJXJGmnFtN4wCW1kKr043Ti+mkMrWy27d/zsiRn/ovfo8mr1ZWcUr6hZrfcWCMSFp9L3nOUfXcWydkYilgJThFLBibXw6QBXPwGvNsyWpzJemM2jbp0FsubqtI8Zk5qbGGvlgQrywyPKy5F7B2hcOOmmQ51psvngpgaETfu9bA/OVXD4UR3ASN2rXhC01UGS47U+QhC9WYCgO7Z29j+MCrUvPIfnaNResauQw1UL4zdxFCml0KrZvj2vOge6N/emboSPcx6kW8cjpgAP45Q/Iy4GgOrK04H1cwQWw8lLdV7twJt2UKU85a0c4qPhcpS5ehqsXWb5kOBzE0UgGlrVusT3qkhFMpQk1y7AKI5yE4of/qRNheqOE6099zjK5wakWEglf8P2jGDglA3OM9U7uUVAGX3HqjwDd5bM+pNAIU0gppzsEggsu0ztM3S1IkjgW2nyNuSQaneCP342sGjP6umDcYSsnNyw+6jVLS06mPGw3VKYDKwHSXpG+oqS+EUr2Zj7hoUzWMj+xUwKf+9ebI5GX0D2L7HNWJzFhu1VieTTmQgDarWR2VOCzG3lk4kzBqSpBdQpKTNIaon7wV9TrJ2QCtEOYm2ehy8OdDxXOhFwP7KsA6rAhyfM+crTPuZNN00RITLuesSfq8O1vvTrS0o6I="

cache:
  directories:
    - $TRAVIS_BUILD_DIR/combined_lib_cache/
    - $TRAVIS_BUILD_DIR/lean-fibonacci/
    - $TRAVIS_BUILD_DIR/natural_number_game/
    - $TRAVIS_BUILD_DIR/dist/
    - $HOME/.elan

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - |
    if [ ! -e "$TRAVIS_BUILD_DIR/combined_lib_cache/leanpkg.toml" ]; then
      cp -av combined_lib/. combined_lib_cache
    fi
  - |
    if [ ! -e "$TRAVIS_BUILD_DIR/lean-fibonacci/leanpkg.toml" ]; then
      git clone https://github.com/bryangingechen/lean-fibonacci.git
    fi
  - |
    if [ ! -e "$TRAVIS_BUILD_DIR/natural_number_game/leanpkg.toml" ]; then
      git clone https://github.com/bryangingechen/natural_number_game.git
    fi
  - source ~/.elan/env
  - source elan_setup.sh
  - mkdir $HOME/scripts || echo ""
  - export PATH="$HOME/scripts:$PATH"
  - cp travis_long.sh $HOME/scripts/travis_long
  - chmod +x $HOME/scripts/travis_long

jobs:
  include:
    - stage: Build-1
      script:
        - |
          if [ $TRAVIS_EVENT_TYPE == 'cron' ]; then
            find . -name *.olean -delete
          fi
        - elan override set leanprover-community/lean:$LATEST_BROWSER_LEAN
        - travis_long "./mk_library.py -c -o dist/libcore.zip"
        - cd combined_lib_cache
        - elan override set leanprover-community/lean:$LATEST_BROWSER_LEAN
        - leanpkg upgrade
        - rm -rf _target/deps/mathlib/scripts
        - rm -rf _target/deps/mathlib/roadmap
        - cd ..
        - travis_long "timeout 2400 ./mk_library.py -i combined_lib_cache" | python detect_errors.py

    - stage: Build-2a
      script:
        - travis_long "timeout 2400 ./mk_library.py -i combined_lib_cache" | python detect_errors.py

    - stage: Build-2b
      script:
        - travis_long "timeout 2400 ./mk_library.py -i combined_lib_cache" | python detect_errors.py

    - stage: Build-3
      script:
        - travis_long "./mk_library.py -i combined_lib_cache"
        - cd lean-fibonacci
        - elan override set leanprover-community/lean:$LATEST_BROWSER_LEAN
        - git pull
        - cd ..
        - travis_long "./mk_library.py -i lean-fibonacci -o dist/libfib.zip"
        - cd natural_number_game
        - elan override set leanprover-community/lean:$LATEST_BROWSER_LEAN
        - git pull
        - git checkout observable
        - cd ..
        - travis_long "./mk_library.py -i natural_number_game -o dist/libnatgame.zip"

    - stage: Deploy
      script:
        - rm -rf .git
        - sh deploy.sh
